/// Flutter icons IconsCs
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  IconsCs
///      fonts:
///       - asset: fonts/IconsCs.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class IconsCs {
  IconsCs._();

  static const _kFontFam = 'IconsCs';
  static const String? _kFontPkg = null;

  static const IconData profil = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pesanan = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData beranda = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData coupon = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
